### ISSUE TITLE
[QUESTION] Synergy Driven Toy Arm Example

### ISSUE THREAD

**Issue by cvhammond** [rcnl-org/nmsm-core#223]
**Is your question related to a problem? Please describe.**
The Synergy Driven Toy Arm example is shared between the nmsm-examples/TrackingOptimization/NewToyArm and /SynergyDrivenToyArmExample. /NewToyArm has Tracking Optimization results and a Verification Optimization XML file that won't converge cleanly. Spencer and I have tried our best to verify the correctness of the cost function terms, but are stumped. Can you please try to get the Verification Optimization to work cleanly and document what you did?

**Have you looked for a solution on [nmsm.rice.edu](https://nmsm.rice.edu)?**
No

**Describe an answer you'd like**
We'd like Verification Optimization to converge in less than 100 iterations.

**Describe alternatives you've considered**
The cost function may not be set up correctly. The data output from Tracking Optimization may not be reorganized correctly for Verification Optimization. We tried moving the TO results into the /preprocessed directory to be used as the input raw data without success.

**Comment by MarlenyVega** [comment]
@cvhammond I just took a look, and the muscle activations and muscle synergies from NCP don't look very good. Can you try rerunning NCP and predict muscle activations (rather than track)? We need smooth muscle activations.
