### ISSUE TITLE
[BUG] GCP parsing crashes if only one contact surface exists

### ISSUE THREAD

**Issue by MarlenyVega** [rcnl-org/nmsm-core#224]
**Describe the bug**
The GCP parsing function crashes when only one contact surface exists. 

**To Reproduce**
1. Go to the gcp example in nmsm-test (RunGCP)
2. Erase the second contact surface so that the first (right foot) contact surface remains
3. Run runGcpFromXml

**Expected behavior**
GCP should be able to handle one contact surface.

**Desktop (please complete the following information):**
 - OS: Windows
 - OpenSim Version: 4.4
 - MATLAB Version: 2022a
 - NMSM Pipeline Version: dev

**Comment by SpencerTWilliams** [comment]
Thanks for pointing that out, fixed in 71b7710a62b311c08416ce0322736d1a269d0a88
