### ISSUE TITLE
[BUG] JMP No Variable Added for X-axis Marker Movement

### ISSUE THREAD

**Issue by bfregly** [rcnl-org/nmsm-core#233]
**Describe the bug**
When I run JMP with X axis marker motion turned on (I am calibrating an ankle joint and tried scaling the tibia body), the initial number of function evaluations reported by the optimizer did not increase from 11 (when no X axis marker motion is selected for the calcaneus). It should increase to 11+3 = 14, since X axis marker movement for 3 markers should add 3 variables to the problem. The result is that adding X axis marker movement has no influence whatsoever on the solution.

**To Reproduce**
1. Run JMP using settings file JMPRAnkleSettingsv3.1.xml, which does not have tibia Y axis marker movement turned on. As shown in file "JMP Convergence 3.1.txt", the final value of the cost function (Resnorm) is 0.324821 after 308 function evaluations.
2. Run JMP again using settings file JMPRAnkleSettingsv3.6.xml, which is identical to JMPRAnkleSettingsv3.6.xml except that calcaneus X axis marker movement has been added. As shown in file "JMP Convergence 3.6.txt", the final value of the cost function (Resnorm) is 0.324821 after 308 function evaluations, which is identical to when no X axis marker movement was added.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - OpenSim Version: 4.4
 - MATLAB Version: 2022a
 - NMSM Pipeline Version: v1.0 beta

**Additional context**
[XAxisMarkerBug.zip](https://github.com/rcnl-org/nmsm-core/files/11952476/XAxisMarkerBug.zip)

**Comment by cvhammond** [comment]
Hmm, there's no body named `calcaneus_r` in the model you attached. 🤔 

I updated the name of the body to `calcn_r` and it seems to work fine. I noticed this one has 5 markers, not 3 as you expect (see #232)
