### ISSUE TITLE
[BUG] JMP Produces Worse Marking Tracking but Lower Cost Function

### ISSUE THREAD

**Issue by bfregly** [rcnl-org/nmsm-core#239]
**Describe the bug**
I just tried running JMP on the scaled UF Subject 5 model using marker data from a single walking cycle, and the results do not make sense.

The starting model is “UF_Subject_5_v2.osim,” which is the model after scaling, and the one cycle gait marker data is “GaitTrial15_markers_jmp.trc."

The settings file GaitTrial15_IK_Settings_Jmp.xml scales the pelvis, both femurs, and both tibias and allows Y axis marker motion in the pelvis, X and Y axis marker motion in both femurs and tibias, and X axis marker motion in both calcaneus and toes bodies. No joint parameters are changed. The JMP cost function drops from 2.63828 to 1.53334 in 7 iterations, producing model “UF_Subject_5_v3b.osim.”

Given the bodies that get modified in the settings file, I expect markers to be tracked for every segment in the model except the forearms and arms.

I expected a visible improvement in marker tracking when I ran IK with the post-JMP model using the same single cycle of gait marker data. However, visual inspecting of the animated skeletons with “Preview Experimental Data” for the marker data revealed that the original model had lower marker tracking errors than did the post-JMP model. The foot shows the most noticeable degradation in marker tracking quality. I can’t get OpenSim to output the marker tracking error file for some reason, despite closing and restarting, so this observation is purely visual. HOWEVER, when you look at the post-JMP model, you will see that the tibias are now SUPER LONG, which is why the marker tracking got noticeably worse.
How can JMP report decreased marker tracking errors when running IK on the same gait cycle marker data using the post-JMP model shows increased marker tracking errors?

**To Reproduce**
See above.

**Expected behavior**
The tibia shouldn't get super long and produce worse marker tracking for the model. Also, JMP should not report better marker tracking when it seems to be worse.

**Screenshots**
Lengthened Tibias.png

**Desktop (please complete the following information):**
 - OS: Windows
 - OpenSim Version: 4.4
 - MATLAB Version: 2023a
 - NMSM Pipeline Version:1.0beta

**Additional context**
[Bug.zip](https://github.com/rcnl-org/nmsm-core/files/11997355/Bug.zip)

**Comment by cvhammond** [comment]
The foot markers didn't get added to the list of markers to track because JMP only adds markers from adjacent bodies. Specifically, the child body of the tibia_r is the talus_r which does not have any markers. If you want to include the markers from the calcn_r, you should include 

```
<JMPBody name="calcn_r">
  <scale_body>false</scale_body>
  <move_markers>false false false<move_markers>
</JMPBody>
```

in the XML settings file.
