### ISSUE TITLE
[BUG] Unrealistic DC Offsets in Some Processed EMG Channels

### ISSUE THREAD

**Issue by bfregly** [rcnl-org/nmsm-core#241]
**Describe the bug**
Following EMG processing, the minimum value of each EMG channel should be zero. However, demeaning a high pass filtered EMG signal may not produce a demeaned signal that varies about zero, since some channels have more positive than negative signal, or vice versa. This situation results in an unrealistic positive or negative offset after rectifying and low pass filtering. Note also that filter artifacts at the start of the trial often produce unrealistically low processed EMG values at the start of the trial, which skews the process of making the minimum value zero. Thus, the minimum value should be determined after skipping the initial region of the processed EMG data.

To fix this issue, here is some proposed code that could go right after lowpass filtering:

% Make minimum value zero, since demeaning a high pass filtered EMG signal
% may not produce a demeaned signal that varies about zero.
% Some EMG signals have more positive than negative signal, or vice versa,
% resulting in an unrealistic positive or negative offset after rectifying
% and low pass filtering. Note also that filter artifacts at the start of
% the trial often produce unrealistically low processed EMG values at the
% start of the trial, which skew the process of making the minimum value
% zero. Thus, the minimum value should be determined after skipping the
% initial region of the processed EMG data, and removal of any remaining
% negative EMG values should be done after this step.
emgData = emgData-ones(size(emgData, 1), 1) * mean(emgData);
emgData = emgData - min(emgData(:,1000:end), [], 2);

**To Reproduce**
Process any EMG data you have laying around and look at the minimum value of each channel after processing.

**Expected behavior**
Unless there is clear continual excitation (which is a possibility for people with spastic muscles), the minimum value of each EMG channel after processing should be zero. How to detect if a muscle excitation is continual due to spasticity is an important question, so maybe this issue will require a bit more investigation and this bug report will just be a placeholder to address it later.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: All
 - OpenSim Version: All
 - MATLAB Version: All
 - NMSM Pipeline Version: 1.0beta

**Additional context**

**Comment by cvhammond** [comment]
Do you want to make a new branch of nmsm-core, make these changes to processEmg.m and submit a PR? We can talk about it tomorrow
