### ISSUE TITLE
[BUG] Muscle-tendon Length Initialization

### ISSUE THREAD

**Issue by bfregly** [rcnl-org/nmsm-core#257]
**Describe the bug**
If tendon slack length goes to zero, the solution blows up.

**To Reproduce**

**Expected behavior**
Solution shouldn't blow up, and tendon slack length should not be allowed to go to zero.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Mac M1, Mac Intel]
 - OpenSim Version: [e.g. 4.4]
 - MATLAB Version: [e.g. 2022b]
 - NMSM Pipeline Version: [e.g. v1.0]

**Additional context**

**Comment by SpencerTWilliams** [comment]
It looks like tendon slack length cannot be zero during the optimization, so I think we may have fixed this already. Do you have an example I should test for this issue, or should we close it?

**Comment by cvhammond** [comment]
Can we isolate the tendon slack length going to zero from the NCP tutorial of the kicking motion? Maybe this issue should be "figure out why the kicking example didn't work as we expected it to"

**Comment by bfregly** [comment]
I found this problem in my own code when I penalized absolute changes in lTs during my own precal process. The problem is that lTs is in the denominator of lMTilda, so the same issue had to exist in the Pipeline code unless lTs had a positive lower bound. You could look at the smallest lTs value present in the Rajagopol model and pick a round number smaller than that as the positive lower bound for all muscles.
