### ISSUE TITLE
[REQUEST] Add <torque_controller_coordinate_list> and implement backend

### ISSUE THREAD

**Issue by cvhammond** [rcnl-org/nmsm-core#260]
@bfregly Can you please clarify our discussion from yesterday regarding an exoskeleton example where both synergy and torque controllers will be used in the same optimal control problem?

Specifically, right now the XML file has a `<states_coordinate_list>` and all other information is inferred from NCP results, .osimx file, etc. 

The issue I'm running into is: How do we indicate which coordinates are torque controlled if our only coordinates element is `<states_coordinate_list>`? I think we need an additional `<torque_controller_coordinate_list>` inside the `<RCNLTorqueController>` element.

Please let me know if this logic is correct for an exoskeleton use case.

**Comment by bfregly** [comment]
Glad to provide input on this important question. Can you point me to the latest XML settings file so that I can answer with the whole design in front of me?

**Comment by cvhammond** [comment]
The live version of the file is [here](https://github.com/rcnl-org/nmsm-examples/blob/main/TreatmentOptimization/TorqueDrivenToyArm/TorqueDrivenTOSettings.xml). I added the `<torque_controller_coordinate_list>` element

**Comment by cvhammond** [comment]
Let's leave this issue up to reference when we implement your suggestions and we can review the implementation then
