### ISSUE TITLE
[REQUEST] Set cutoff frequency for Treatment Optimization initial state derivatives

### ISSUE THREAD

**Issue by SpencerTWilliams** [rcnl-org/nmsm-core#270]
**Is your feature request related to a problem? Please describe.**
For simple motions, like the Toy Arm example, the hard-coded B-spline cutoff frequency of 10 Hz produces unrealistic results. 

**Describe the solution you'd like**
XML settings files should have a field for setting the cutoff frequency. Determining the number of B-spline nodes to use for derivatives will work exactly as it does in GCP. 

**Describe alternatives you've considered**
As there is no single cutoff frequency that will work for all motions, this feature is needed.

**Comment by cvhammond** [comment]
a switch to `spaps(...)` for `makeExperimentalDataSplines.m` solves this issue
