### ISSUE TITLE
[BUG] reportDistanceErrorByMarker not reporting correct errors

### ISSUE THREAD

**Issue by RobSalati** [rcnl-org/nmsm-core#312]
**Describe the bug**
reportDistanceErrorByMarker does not properly respond to changes in the markerNames argument. Changing the order in markerNames does not change the corresponding order of the data columns in the output .sto file, it only changes the column labels.

**To Reproduce**
1) Go to JMP Tutorial
2) Run the plot and analyze data block & save the output figure
3) Change the order of the markers in markerNames
4) Run the plot and analyze data block again 
5) Note that the plots are exactly the same with the exception of the legends

**Expected behavior**
reportDistanceErrorByMarker should change the order of the data columns when the order of marker inputs is changed, rather than just changing the column label and nothing else

**Screenshots**
![image](https://github.com/rcnl-org/nmsm-core/assets/142843461/22963ad5-4b90-4b85-a1d3-78f818ffd3b7)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - OpenSim Version: 4.5
 - MATLAB Version: 2023a
 - NMSM Pipeline Version: V 1.1

**Comment by cvhammond** [comment]
fixed on `dev`
