### ISSUE TITLE
[BUG] Treatment optimization incorrectly reads initial guess GRF into experimental GRF

### ISSUE THREAD

**Issue by RobSalati** [rcnl-org/nmsm-core#326]
**Describe the bug**
When parsing ground reactions, treatment optimization reads data from the initial guess directory into inputs.contactSurfaces{i}.experimentalGroundReactionForces. This results in the initial guess ground reactions being tracked instead of the tracked data ground reactions. 

**To Reproduce**
1) Run TO with initial guess ground reactions and tracked data ground reactions that are noticeably different
2) Place a breakpoint at line 36 in TrackingOptimizationTool
3) run commands:
>> plot(inputs.contactSurfaces{1,1}.experimentalGroundReactionForces)
>> figure()
>> plot(inputs.contactSurfaces{1,1}.initialGroundReactionForces)
These 2 plots will look exactly the same, which is incorrect.

**Expected behavior**
The experimental ground reactions should be read from tracked data directory, not initial guess directory. 

**Screenshots**
This is the plot produced from a TO run after I cancelled it in the middle, and used the cancelled results as the initial guess. The blue line should be the experimental data, but is instead the ground reactions from the cancelled run.
![untitled](https://github.com/user-attachments/assets/b633a46e-57cf-43b2-952b-5c6c5f300c67)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - MATLAB Version: 2023a
 - NMSM Pipeline Version: V1.2 (dev)

**Additional context**
I think this can be fixed by switching lines 191-192 with 194-195 in parseTreatmentOptimizationDataDirectory.

**Comment by SpencerTWilliams** [comment]
Fixed in #333, thanks!
